### PR TITLE
DevOps: Unit-test clean_gsheet_data

### PR DESCRIPTION
**Pull request by avisionh**
# Summary
This branch adds unit-testing to the repo. In particular, it adds it and rudimentary tests the `clean_gsheet_data` function to ensure it gives the desired result.

# Check
- [ ] The tests pass.
    + Click *Run Tests* in the top-right of the below screenshot.
image

### CODE REVIEW

**Comment by martinctc** [comment]
The tests are failing for me because of `Error: object 'xuan_qu_constituency' not found`. I think this is because the Chinese character column names when defined with `data.frame()` does not end up with the same input as you would have when you read directly from a Google Sheet.

**Comment by avisionh** [comment]
> The tests are failing for me because of `Error: object 'xuan_qu_constituency' not found`. I think this is because the Chinese character column names when defined with `data.frame()` does not end up with the same input as you would have when you read directly from a Google Sheet.

Interesting! Any clue as to how one can resolve this? Is it pinyin? Perhaps @gabtam55 might know.

**Comment by martinctc** [comment]
> > The tests are failing for me because of `Error: object 'xuan_qu_constituency' not found`. I think this is because the Chinese character column names when defined with `data.frame()` does not end up with the same input as you would have when you read directly from a Google Sheet.
> 
> Interesting! Any clue as to how one can resolve this? Is it pinyin? Perhaps @gabtam55 might know.

It's to do with the locale I think. Because the specific error message is:

`Error: \uxxxx sequences not supported inside backticks`

See this discussion (answer at the bottom): https://github.com/rstudio/rstudio/issues/3496

**Comment by avisionh** [comment]
> > > The tests are failing for me because of `Error: object 'xuan_qu_constituency' not found`. I think this is because the Chinese character column names when defined with `data.frame()` does not end up with the same input as you would have when you read directly from a Google Sheet.
> > 
> > 
> > Interesting! Any clue as to how one can resolve this? Is it pinyin? Perhaps @gabtam55 might know.
> 
> It's to do with the locale I think. Because the specific error message is:
> 
> `Error: \uxxxx sequences not supported inside backticks`
> 
> See this discussion (answer at the bottom): [rstudio/rstudio#3496](https://github.com/rstudio/rstudio/issues/3496)

Hmmm...I think setting the user's device locale is a bad idea since it might mess up their other stuff like their clock. I think a better approach is to use the Chinese characters for `xuan_qu` or `xuan_qu_hao_ma`. Do you know what they are? The original Google Sheet seems to have disappeared from the GDrive.

**Comment by martinctc** [comment]
> > > > The tests are failing for me because of `Error: object 'xuan_qu_constituency' not found`. I think this is because the Chinese character column names when defined with `data.frame()` does not end up with the same input as you would have when you read directly from a Google Sheet.
> > > 
> > > 
> > > Interesting! Any clue as to how one can resolve this? Is it pinyin? Perhaps @gabtam55 might know.
> > 
> > 
> > It's to do with the locale I think. Because the specific error message is:
> > `Error: \uxxxx sequences not supported inside backticks`
> > See this discussion (answer at the bottom): [rstudio/rstudio#3496](https://github.com/rstudio/rstudio/issues/3496)
> 
> Hmmm...I think setting the user's device locale is a bad idea since it might mess up their other stuff like their clock. I think a better approach is to use the Chinese characters for `xuan_qu` or `xuan_qu_hao_ma`. Do you know what they are? The original Google Sheet seems to have disappeared from the GDrive.

I actually did use the original Chinese characters, but they reverted to the \uxxxx when you pass it into R as a data frame. The original Google Sheets are saved here: https://docs.google.com/spreadsheets/d/1usk9Q-5lA4bL_z6KXpUohc_2x_KhDgLxtm-YEtim_yk/

One thought to discuss: since the Google Sheet itself was completely accidental that the columns are named as such (in this odd format where it is `選區\nConstituency` which is not best practice anyway), and that this function was an ad-hoc one-time solution to address this format, does it still make sense to create a unit test for this function? My thinking is that this function is more of an explication of the cleaning and reasoning steps we used for our ad-hoc data cleaning problem, and if any other user were to try to re-use our function, they would have to make adjustments to it depending on how the data is formatted. By this reasoning, the more helpful thing we can do for users is to add more explanation in the comments on what each step of the function is doing. One of my assumptions is that the Google Sheet itself is not really 'reproducible', in the sense that the format or the links could change or break easily in the future, therefore making the exercise of unit testing not particularly helpful for the user if what we're trying to do is to provide a record of how they can reproduce the work (with slightly different data).

**Comment by avisionh** [comment]
> I actually did use the original Chinese characters, but they reverted to the \uxxxx when you pass it into R as a data frame. The original Google Sheets are saved here: https://docs.google.com/spreadsheets/d/1usk9Q-5lA4bL_z6KXpUohc_2x_KhDgLxtm-YEtim_yk/
> 
> One thought to discuss: since the Google Sheet itself was completely accidental that the columns are named as such (in this odd format where it is `選區\nConstituency` which is not best practice anyway), and that this function was an ad-hoc one-time solution to address this format, does it still make sense to create a unit test for this function? My thinking is that this function is more of an explication of the cleaning and reasoning steps we used for our ad-hoc data cleaning problem, and if any other user were to try to re-use our function, they would have to make adjustments to it depending on how the data is formatted. By this reasoning, the more helpful thing we can do for users is to add more explanation in the comments on what each step of the function is doing. One of my assumptions is that the Google Sheet itself is not really 'reproducible', in the sense that the format or the links could change or break easily in the future, therefore making the exercise of unit testing not particularly helpful for the user if what we're trying to do is to provide a record of how they can reproduce the work (with slightly different data).

You make very good points, especially with the more general bad practice of `選區\nConstituency` not being best practice. The idea behind unit-testing this function is so we can check that the function works in the way it intends to. Is the function worth testing? I think it is if we still need to actively use it to generate the final data that goes into the `hkdatasets` package. However, since we are not going to be actively using it in the near future and that by the time it comes to update the data, it would have probably been changed, then it's not worth the effort to invest further time in this.

**Pull request closed without merging**
