### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by gabtam55**
## Changes in this Pull Request

This pull request increments the package version to 0.0.3 from 0.0.2.

1. The 4 variables (i.e. `Political`, `Camp`, `Gender`, `Tag`) from the `hkdc` dataset have been translated into English.
1. R documentation for the `hkdc` dataset has been updated accordingly.
1. The script used to translate is saved under `.dev/script`.
1. The translation table used to translate the `Political` variable is saved under `.dev/data`.
1. `devtools::check()` did not identify any errors
1. `devtools:install()` installed package to local machine successfully

### CODE REVIEW

**Comment by gabtam55** [comment]
[Improve {hkdatasets} package](https://trello.com/c/JY21zbtU/48-improve-hkdatasets-package)

**Comment by avisionh** [comment]
Thanks for this, putting some initial feedback before looking at this in more detail:
1. Did you add `renv` to it? If so, can you specify in the PR description at the top?
    + Also, can you add it to the DESCRIPTION file? It should be as easy as running in the R terminal, `usethis::use_package(package = 'renv', type = 'Imports')`
1. Typically, we do not version-control the following files because they do not impact on the code. Could you add them to the `.gitignore` file and commit, then delete these files from the repo?
    + `.DS_Store` - this is a file related to how file icons are arranged on your Finder.
    + `.RHistory` - this is a file of all the history of the R code you ran in the terminal.
11. For the `dev/script/translation090920.R` file, can you remove the date from the file name? Things like date should be captured automatically by git so no need for it to be in the file name itself.

**Comment by gabtam55** [comment]
> Thanks for this, putting some initial feedback before looking at this in more detail:
> 
> 1. Did you add `renv` to it? If so, can you specify in the PR description at the top?
>    
>    * Also, can you add it to the DESCRIPTION file? It should be as easy as running in the R terminal, `usethis::use_package(package = 'renv', type = 'Imports')`
> 2. Typically, we do not version-control the following files because they do not impact on the code. Could you add them to the `.gitignore` file and commit, then delete these files from the repo?
>    
>    * `.DS_Store` - this is a file related to how file icons are arranged on your Finder.
>    * `.RHistory` - this is a file of all the history of the R code you ran in the terminal.
> 3. For the `dev/script/translation090920.R` file, can you remove the date from the file name? Things like date should be captured automatically by git so no need for it to be in the file name itself.

Thanks a lot for the comments Avision. They are very useful for me to understand git workflow better. By the way, can I ask why I could only see the .dev folder on GitHub web but not on GitHub Desktop?

**Comment by martinctc** [comment]
So I have a question to raise about `renv` here - since we do not use any functions at all as part of the package itself, ought this not be a pretty 'blank slate' when we run `renv::restore()`? We seem to be requiring a whole bunch of unnecessary packages when you look into `renv.lock`. @gabtam55 @avisionh

**Comment by gabtam55** [comment]
> So I have a question to raise about `renv` here - since we do not use any functions at all as part of the package itself, ought this not be a pretty 'blank slate' when we run `renv::restore()`? We seem to be requiring a whole bunch of unnecessary packages when you look into `renv.lock`. @gabtam55 @avisionh

You are probably right. Should I do the following?
- run `renv::deactivate()`
- delete `renv` folder and `renv.lock` from the repo
- remove the mention of `renv` from the DESCRIPTION file

**Comment by avisionh** [comment]
> Thanks a lot for the comments Avision. They are very useful for me to understand git workflow better. By the way, can I ask why I could only see the .dev folder on GitHub web but not on GitHub Desktop?

Certainly, any folder or file that's named with a `.` at the beginning is actually hidden automatically by your file management system (Finder for macOS and File Explorer for Windows OS). You can change the settings of your file management system so that it shows the hidden folders/files. This is probably why GitHub Desktop cannot see it. However, you can probably change the settings in your GitHub Desktop to show these hidden files.

> > So I have a question to raise about `renv` here - since we do not use any functions at all as part of the package itself, ought this not be a pretty 'blank slate' when we run `renv::restore()`? We seem to be requiring a whole bunch of unnecessary packages when you look into `renv.lock`. @gabtam55 @avisionh
> 
> You are probably right. Should I do the following?
> 
> * run `renv::deactivate()`
> * delete `renv` folder and `renv.lock` from the repo
> * remove the mention of `renv` from the DESCRIPTION file

After thinking about this hard, yes, I think @martinctc is right. Those are the steps I would take, though I would probably also add the step to put the packages mentioned in the [scripts/](https://github.com/Hong-Kong-Districts-Info/hkdatasets/tree/master/.dev/script) as 'Suggests' for the `DESCRIPTION` file. 

For example, with `.dev/script/generate_data_collisions.R`
```r
usethis::use_package(package = 'hk80', type = 'Suggests')
```

**Comment by gabtam55** [comment]
> > Thanks a lot for the comments Avision. They are very useful for me to understand git workflow better. By the way, can I ask why I could only see the .dev folder on GitHub web but not on GitHub Desktop?
> 
> Certainly, any folder or file that's named with a `.` at the beginning is actually hidden automatically by your file management system (Finder for macOS and File Explorer for Windows OS). You can change the settings of your file management system so that it shows the hidden folders/files. This is probably why GitHub Desktop cannot see it. However, you can probably change the settings in your GitHub Desktop to show these hidden files.
> 
> > > So I have a question to raise about `renv` here - since we do not use any functions at all as part of the package itself, ought this not be a pretty 'blank slate' when we run `renv::restore()`? We seem to be requiring a whole bunch of unnecessary packages when you look into `renv.lock`. @gabtam55 @avisionh
> > 
> > 
> > You are probably right. Should I do the following?
> > 
> > * run `renv::deactivate()`
> > * delete `renv` folder and `renv.lock` from the repo
> > * remove the mention of `renv` from the DESCRIPTION file
> 
> After thinking about this hard, yes, I think @martinctc is right. Those are the steps I would take, though I would probably also add the step to put the packages mentioned in the [scripts/](https://github.com/Hong-Kong-Districts-Info/hkdatasets/tree/master/.dev/script) as 'Suggests' for the `DESCRIPTION` file.
> 
> For example, with `.dev/script/generate_data_collisions.R`
> 
> ```r
> usethis::use_package(package = 'hk80', type = 'Suggests')
> ```

Thanks for feedback. Renv removed and packages mentioned added to the DESCRIPTION file. Do not merge just yet though as @martinctc has made another submission to CRAN. :)

**Comment by martinctc** [comment]
> Thanks for feedback. Renv removed and packages mentioned added to the DESCRIPTION file. Do not merge just yet though as @martinctc has made another submission to CRAN. :)

We can merge, but be sure to increment the version on DESCRIPTION so that we make it out as 0.0.3 (the version submitted to CRAN is 0.0.2). 

Also, checks are now failing because of `renv`...

**Comment by martinctc** [comment]
> > Thanks for feedback. Renv removed and packages mentioned added to the DESCRIPTION file. Do not merge just yet though as @martinctc has made another submission to CRAN. :)
> 
> We can merge, but be sure to increment the version on DESCRIPTION so that we make it out as 0.0.3 (the version submitted to CRAN is 0.0.2).
> 
> Also, checks are now failing because of `renv`...

Found the issue - this has to do with the reference to `renv` in .Rprofile, have removed this in the latest commit.

**Comment by martinctc** [comment]
Have incremented the package version to 0.0.3, and now all checks are passing! Thanks for all the hard work @gabtam55 and @avisionh - will merge this in! 😄

**Pull request merged**
