### PR TITLE
Feature: New data additions

### PR DESCRIPTION
**Pull request by martinctc**
# Summary
This branch includes new additions to **hkdatasets**.

# Changes
The changes made in this PR are:
1. Added a new dataset `hkstreetnames20`, providing a list of Hong Kong street names as of 2020.
1. Added a new dataset `hkdistrict_summary`.
1. Added a new dataset `hkagepop19`, which shows the break down of total population by age and district, updated as of 2019 (provided by the Census and Statistics Department.
1. Fixed some broken Facebook links in `hkdc`, with special thanks to @elgarteo.

***

# Check
- [x] All the documentation is clear and present.
- [x] The R CMD checks pass.

***

## Note
This fixes issues #6.

### CODE REVIEW

**Comment by gabtam55** [comment]
Looks good to me. Made some small changes on the documentations for hkagepop19 and hkstreetnames20.

Btw,
- What should I have done in github if I wanted to specifically ask you to look at the files that I changed, after creating a commit in github desktop?
- Is there any way to 'delete' a commit that was pushed from github desktop accidentally?

Thanks!

**Review by gabtam55 — APPROVED** [review]

**Comment by martinctc** [comment]
> Looks good to me. Made some small changes on the documentations for hkagepop19 and hkstreetnames20.
> 
> Btw,
> 
> * What should I have done in github if I wanted to specifically ask you to look at the files that I changed, after creating a commit in github desktop?
> * Is there any way to 'delete' a commit that was pushed from github desktop accidentally?
> 
> Thanks!

Sorry - didn't have a chance to look at this until now. You can click into your commit, find that specific file, and you can click on the code to add comments like in this screenshot: 

image

There is a way to 'delete a commit' via `git revert` - there's a good article to read here: <https://opensource.com/article/18/6/git-reset-revert-rebase-commands>. However, this will have to be done via git CLI I believe, as opposed to GitHub Desktop. 

I usually just do a new commit to 'reverse' my changes, which although might not be best practice, is the most fail-safe way of undoing changes I'd say. 

I might have another look at the data to see if there are any annotations I can add, and then I'll merge this PR.

**Comment by gabtam55** [comment]
> > Looks good to me. Made some small changes on the documentations for hkagepop19 and hkstreetnames20.
> > Btw,
> > 
> > * What should I have done in github if I wanted to specifically ask you to look at the files that I changed, after creating a commit in github desktop?
> > * Is there any way to 'delete' a commit that was pushed from github desktop accidentally?
> > 
> > Thanks!
> 
> Sorry - didn't have a chance to look at this until now. You can click into your commit, find that specific file, and you can click on the code to add comments like in this screenshot:
> 
> image
> 
> There is a way to 'delete a commit' via `git revert` - there's a good article to read here: https://opensource.com/article/18/6/git-reset-revert-rebase-commands. However, this will have to be done via git CLI I believe, as opposed to GitHub Desktop.
> 
> I usually just do a new commit to 'reverse' my changes, which although might not be best practice, is the most fail-safe way of undoing changes I'd say.
> 
> I might have another look at the data to see if there are any annotations I can add, and then I'll merge this PR.

Thanks mate!
<> test 123

**Comment by martinctc** [comment]
@gabtam55 I've made some tidying up to the documentation and merged @elgarteo's updated Facebook links - will merge this in once the R CMD checks pass.

**Pull request merged**
